- name: Set hostname
  become: yes
  shell: hostname {{node_name}} && echo {{ node_name }} > /etc/hostname

- name: Install socat for Ubuntu server
  become: yes
  apt: name={{ item }} state=latest
  with_items:
  - socat
  when: ansible_distribution == "Ubuntu"
     
- name: Install socat for Centos server
  become: yes
  yum: name={{ item }} state=latest
  with_items:
  - socat
  when: ansible_distribution == "CentOS"

- name: Disable firewalld on Centos server
  become: yes
  service: name=firewalld state=stopped enabled=no
  when: ansible_distribution == "CentOS"

- name: Flush iptables 
  become: yes
  shell: iptables -P FORWARD ACCEPT

- name: Disable swap
  become: yes
  shell: swapoff -a

- name: Remove swap config from /etc/fstab
  become: yes
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    state: absent
    backup: 'yes'

- name: Set hosts
  become: yes
  template: src=hosts.j2 dest=/etc/hosts 

- name: Disable selinux on Centos server temporarily
  become: yes
  shell: "setenforce 0"
  when: ansible_distribution == "CentOS"

- name: Disable selinux on Centos server 
  become: yes
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"
  when: ansible_distribution == "CentOS"


- name: Change sysctl config
  become: yes
  copy: src=k8s-sysctl.conf.j2 dest=/etc/sysctl.d/k8s-sysctl.conf

- name: Enable br_netfilter module
  become: yes
  modprobe: name=br_netfilter state=present
  ignore_errors: true
  
- name: Reload sysctl config
  become: yes
  shell: "sysctl -p /etc/sysctl.d/k8s-sysctl.conf"
  ignore_errors: true
